# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ea7JwXKr6dakTdsdqukU7Mrl-7AZYGb
"""

import streamlit as st
import numpy as np
import librosa
import librosa.display
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pickle
import io
import base64
import json
import yaml
import os
from datetime import datetime
from yaml.loader import SafeLoader

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="InstruNet AI",
    page_icon="🎵",
    layout="wide",
    initial_sidebar_state="collapsed"
)

QUALITY_LABELS   = ['excellent', 'good', 'fair', 'poor']
CONDITION_LABELS = ['modern', 'clean', 'noisy', 'vintage']

CONFIG_FILE = "auth_config.yaml"

def load_config() -> dict:
    """Load auth config from file, or build a fresh one from Streamlit Secrets."""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE) as f:
            return yaml.load(f, Loader=SafeLoader)

    # Bootstrap from Streamlit Secrets if no file yet
    try:
        seed_users = dict(st.secrets.get("seed_users", {}))
    except Exception:
        seed_users = {}

    config = {
        "credentials": {"usernames": {}},
        "cookie": {
            "name":     "instrunet_auth",
            "key":      st.secrets.get("COOKIE_KEY", "instrunet_super_secret_key_2026"),
            "expiry_days": 30
        },
        "pre-authorized": {"emails": []}
    }

    # Add any seed users from secrets (their passwords must already be bcrypt-hashed)
    for uname, hpw in seed_users.items():
        config["credentials"]["usernames"][uname] = {
            "name": uname.capitalize(),
            "email": f"{uname}@instrunet.ai",
            "password": hpw,
            "failed_login_attempts": 0,
            "logged_in": False
        }

    save_config(config)
    return config


def save_config(config: dict):
    """Persist the config back to disk."""
    with open(CONFIG_FILE, "w") as f:
        yaml.dump(config, f, default_flow_style=False)


# ─────────────────────────────────────────────────────────────────────────────
# MODEL LOADER
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_model_and_encoder():
    from huggingface_hub import hf_hub_download
    from tensorflow import keras
    token   = st.secrets["HF_TOKEN"]
    repo_id = st.secrets["HF_REPO_ID"]
    model_path   = hf_hub_download(repo_id=repo_id, filename="best_multitask_model.keras", token=token)
    encoder_path = hf_hub_download(repo_id=repo_id, filename="label_encoder.pkl", token=token)
    model = keras.models.load_model(model_path)
    with open(encoder_path, 'rb') as f:
        encoder = pickle.load(f)
    return model, encoder


INSTRUMENT_ICONS = {
    'brass':'🎺','guitar':'🎸','keyboard':'🎹','mallet':'🪘',
    'organ':'🎹','reed':'🎷','string':'🎻','synth':'🎛️',
    'vocal':'🎤','flute':'🪈','bass':'🎸','drum':'🥁'
}
def get_icon(name):
    n = (name or '').lower()
    for k, v in INSTRUMENT_ICONS.items():
        if k in n: return v
    return '🎵'


# ─────────────────────────────────────────────────────────────────────────────
# CSS
# ─────────────────────────────────────────────────────────────────────────────
def inject_css(dark: bool):
    if dark:
        bg=("#0d0d14"); surface=("#15151f"); surface2=("#1c1c28"); border=("#2a2a3d")
        text=("#e4e4f0"); muted=("#64648a"); accent=("#7c6af7"); accent2=("#a78bfa")
        hgrad="linear-gradient(135deg,#1e1b4b,#312e81)"; shadow="0 8px 32px rgba(0,0,0,.55)"
        btrk=("#252535"); hrog="linear-gradient(135deg,#13132a,#1a1635,#13132a)"
        tblue=("#0d1120"); tpurp=("#120d20"); tindi=("#0e1020")
        snbg=("#1a0c0c"); snbd=("#7f1d1d"); scbg=("#0c1a15"); scbd=("#064e3b")
        fbg=("#08080e"); lbg="radial-gradient(ellipse at 25% 25%,#1e1b4b,#0d0d14 55%,#1a0d2e)"
        lcrd=("#13131d"); lbrd=("#25253a"); ibg=("#1a1a28"); ibd=("#35355a")
        ifsh="rgba(124,106,247,.25)"
    else:
        bg=("#f0f0f7"); surface=("#ffffff"); surface2=("#f7f7fc"); border=("#e2e2ee")
        text=("#111118"); muted=("#9090aa"); accent=("#5b50e8"); accent2=("#764ba2")
        hgrad="linear-gradient(135deg,#667eea,#764ba2)"; shadow="0 10px 40px rgba(0,0,0,.08)"
        btrk=("#e2e2ee"); hrog="linear-gradient(135deg,#eff0ff,#f5f0ff,#eef0ff)"
        tblue=("#eef3ff"); tpurp=("#f3eeff"); tindi=("#eef0ff")
        snbg=("#fff1f2"); snbd=("#fecaca"); scbg=("#f0fff9"); scbd=("#99f6e4")
        fbg=("#111118"); lbg="radial-gradient(ellipse at 25% 25%,#667eea,#4f46e5 40%,#764ba2)"
        lcrd=("#ffffff"); lbrd=("#e2e2ee"); ibg=("#ffffff"); ibd=("#c8c8dd")
        ifsh="rgba(91,80,232,.18)"

    st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap');
:root{{
  --bg:{bg};--surface:{surface};--surface2:{surface2};--border:{border};
  --text:{text};--muted:{muted};--accent:{accent};--accent2:{accent2};
  --shadow:{shadow};--btrk:{btrk};
}}
*{{font-family:'DM Sans',sans-serif!important;box-sizing:border-box;}}
#MainMenu,footer,header{{visibility:hidden;}}
.block-container{{padding:0!important;max-width:100%!important;}}
section[data-testid="stSidebar"]{{display:none!important;}}
[data-testid="stAppViewContainer"],[data-testid="stMain"]{{background:var(--bg)!important;}}

/* ── AUTH WRAPPER ── */
.auth-page{{
  min-height:100vh;background:{lbg};
  display:flex;align-items:center;justify-content:center;
  padding:2rem;position:relative;overflow:hidden;
}}
.auth-page::before{{
  content:'';position:absolute;inset:0;pointer-events:none;
  background:url("data:image/svg+xml,%3Csvg width='60' height='60' xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle cx='30' cy='30' r='1.5' fill='%23ffffff' fill-opacity='0.04'/%3E%3C/svg%3E");
}}
.orb{{position:absolute;border-radius:50%;filter:blur(90px);opacity:.28;pointer-events:none;animation:drift 14s ease-in-out infinite alternate;}}
.orb1{{width:380px;height:380px;background:#7c6af7;top:-110px;left:-80px;animation-delay:0s;}}
.orb2{{width:260px;height:260px;background:#a855f7;bottom:-70px;right:-50px;animation-delay:-5s;}}
.orb3{{width:160px;height:160px;background:#3b82f6;top:45%;right:16%;animation-delay:-9s;}}
@keyframes drift{{from{{transform:translate(0,0)}}to{{transform:translate(22px,30px)}}}}

.auth-card{{
  background:{lcrd};border:1px solid {lbrd};border-radius:1.6rem;
  padding:2.6rem 2.4rem;width:100%;max-width:440px;
  position:relative;z-index:1;box-shadow:0 28px 90px rgba(0,0,0,.35);
  animation:cardIn .65s cubic-bezier(.16,1,.3,1) forwards;
}}
@keyframes cardIn{{from{{opacity:0;transform:translateY(28px) scale(.96)}}to{{opacity:1;transform:none}}}}

.auth-logo{{
  text-align:center;margin-bottom:1.8rem;
}}
.auth-logo-icon{{
  display:inline-flex;align-items:center;justify-content:center;
  width:66px;height:66px;border-radius:1.2rem;font-size:1.85rem;
  background:linear-gradient(135deg,{accent},{accent2});
  box-shadow:0 8px 28px {accent}55;margin-bottom:.85rem;
}}
.auth-brand{{font-family:'Syne',sans-serif!important;font-size:1.7rem;font-weight:800;color:{text};letter-spacing:-.04em;margin:0;}}
.auth-brand span{{color:{accent};}}
.auth-tag{{font-size:.71rem;color:{muted};margin:.32rem 0 0;font-weight:500;text-transform:uppercase;letter-spacing:.08em;}}

/* tab switcher */
.tab-row{{display:flex;background:{surface2};border-radius:.85rem;padding:.3rem;gap:.3rem;margin-bottom:1.5rem;border:1px solid {border};}}
.tab-btn{{
  flex:1;padding:.55rem;border-radius:.6rem;border:none;cursor:pointer;
  font-weight:600;font-size:.85rem;transition:all .2s;background:transparent;color:{muted};
}}
.tab-btn.active{{background:{accent};color:white;box-shadow:0 4px 14px {accent}44;}}

/* ── MAIN APP ── */
.hdr{{background:{hgrad};color:white;padding:1.4rem 2.5rem;}}
.hdr h1{{font-family:'Syne',sans-serif!important;font-size:2.1rem;font-weight:800;margin:0 0 .12rem;letter-spacing:-.04em;}}
.hdr h1 span{{opacity:.55;font-weight:400;}}
.hdr p{{color:rgba(255,255,255,.58);margin:0;font-size:.87rem;}}
.tag-row{{display:flex;gap:.45rem;margin-top:.65rem;flex-wrap:wrap;}}
.tag-pill{{background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.2);border-radius:9999px;padding:.18rem .75rem;font-size:.7rem;font-weight:600;color:white;letter-spacing:.04em;}}

.ubar{{display:flex;align-items:center;gap:.6rem;padding:.5rem 2.5rem;background:{surface2};border-bottom:1px solid {border};}}
.ubar-info{{flex:1;font-size:.79rem;color:{muted};}}
.ubar-info strong{{color:{text};}}

.wrap{{padding:1.75rem 2.5rem;background:var(--bg);}}
.card{{background:var(--surface);border:1px solid var(--border);border-radius:1.1rem;box-shadow:var(--shadow);padding:1.4rem;margin-bottom:1.4rem;}}
.card h3{{font-family:'Syne',sans-serif!important;font-size:.97rem;font-weight:700;color:var(--text);margin:0 0 1rem;}}

.bar-row{{margin-bottom:.68rem;}}
.bar-label{{display:flex;justify-content:space-between;font-size:.79rem;margin-bottom:.2rem;}}
.bar-track{{background:var(--btrk);border-radius:9999px;overflow:hidden;}}
.bar-fill{{border-radius:9999px;transition:width 1.2s cubic-bezier(.4,0,.2,1);}}

.qbadge{{display:inline-block;padding:.3rem .9rem;border-radius:9999px;font-weight:700;font-size:.74rem;letter-spacing:.05em;}}
.q-excellent{{background:#10b981;color:white}}.q-good{{background:#3b82f6;color:white}}
.q-fair{{background:#f59e0b;color:white}}.q-poor{{background:#ef4444;color:white}}

.hero-wrap{{background:{hrog};border-radius:1rem;padding:2.2rem;display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:2.4rem;margin-bottom:1.35rem;text-align:center;border:1px solid var(--border);}}
.hero-icon{{font-size:4.5rem;line-height:1;margin-bottom:.4rem;}}
.hero-name{{font-family:'Syne',sans-serif!important;font-size:2.7rem;font-weight:800;color:var(--text);letter-spacing:-.04em;line-height:1;}}
.hero-sub{{font-size:.69rem;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:.1em;margin-top:.32rem;}}
.ch{{color:#10b981;font-size:1.05rem;font-weight:700;margin-top:.42rem;}}
.cm{{color:#f59e0b;font-size:1.05rem;font-weight:700;margin-top:.42rem;}}
.cl{{color:#ef4444;font-size:1.05rem;font-weight:700;margin-top:.42rem;}}

.pgrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:.85rem;margin-top:.85rem;}}
@media(max-width:640px){{.pgrid{{grid-template-columns:1fr;}}}}
.pcard{{border-radius:.85rem;padding:1.05rem;border:1.5px solid var(--border);background:var(--surface2);}}
.pcard.win{{border-color:{accent};background:{"#13103a" if dark else "#f0eeff"};}}
.rbadge{{display:inline-block;padding:.12rem .52rem;border-radius:9999px;font-size:.69rem;font-weight:700;margin-bottom:.68rem;}}
.r1{{background:{accent};color:white;}}.rn{{background:var(--btrk);color:var(--muted);}}

.sigbox{{border-radius:.85rem;padding:.88rem 1.05rem;display:flex;align-items:center;justify-content:space-between;margin-bottom:.68rem;}}
.snoisy{{background:{snbg};border:1px solid {snbd};}}.sclean{{background:{scbg};border:1px solid {scbd};}}

.igrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:.85rem;margin-bottom:1.35rem;}}
.itile{{border-radius:.85rem;padding:.88rem;text-align:center;border:1px solid var(--border);}}
.t-ico{{font-size:1.22rem;margin-bottom:.22rem;}}.t-lbl{{font-size:.66rem;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);font-weight:600;}}
.t-val{{font-size:.98rem;font-weight:800;color:var(--text);margin-top:.1rem;}}
.tb{{background:{tblue};}}.tp{{background:{tpurp};}}.ti{{background:{tindi};}}
.viz-img{{width:100%;border-radius:.85rem;border:1px solid var(--border);}}
.ftr{{background:{fbg};color:{"#3a3a5a" if dark else "#6b7280"};text-align:center;padding:1.35rem;font-size:.77rem;margin-top:2rem;border-top:1px solid {border};}}

/* streamlit input */
.stTextInput>div>div>input{{
  background:{ibg}!important;border:1.5px solid {ibd}!important;border-radius:.8rem!important;
  color:{text}!important;font-size:.92rem!important;padding:.7rem 1rem!important;transition:border-color .2s!important;
}}
.stTextInput>div>div>input:focus{{border-color:{accent}!important;box-shadow:0 0 0 3px {ifsh}!important;}}
.stTextInput label{{color:{text}!important;font-weight:600!important;font-size:.82rem!important;}}

/* checkbox (remember me) */
.stCheckbox label{{color:{text}!important;font-size:.84rem!important;font-weight:500!important;}}
.stCheckbox>div>label>span:first-child{{border-color:{ibd}!important;background:{ibg}!important;border-radius:.4rem!important;}}

/* file uploader */
[data-testid="stFileUploadDropzone"]{{
  border:2px dashed {"#35355a" if dark else "#c8c8dd"}!important;
  border-radius:1rem!important;background:{surface2}!important;transition:all .3s!important;
}}
[data-testid="stFileUploadDropzone"]:hover{{border-color:{accent}!important;background:{"#171730" if dark else "#eeeeff"}!important;}}
[data-testid="stFileUploadDropzone"] label,[data-testid="stFileUploadDropzone"] p,
[data-testid="stFileUploadDropzone"] span{{color:{muted}!important;font-weight:500!important;}}

/* main button */
.stButton>button{{
  background:linear-gradient(135deg,{accent},{accent2})!important;color:white!important;
  font-weight:700!important;font-size:.92rem!important;border-radius:9999px!important;
  border:none!important;padding:.78rem 2.6rem!important;
  transition:transform .15s,box-shadow .15s!important;
  font-family:'Syne',sans-serif!important;letter-spacing:.02em!important;
}}
.stButton>button:hover{{transform:scale(1.04)!important;box-shadow:0 8px 28px {accent}55!important;}}
.stButton>button:disabled{{background:{"#252535" if dark else "#e2e2ee"}!important;color:{"#45455a" if dark else "#a0a0b8"}!important;transform:none!important;}}

/* download buttons */
.stDownloadButton>button{{
  border-radius:.85rem!important;font-weight:700!important;padding:.66rem 1.35rem!important;
  border:1.5px solid var(--border)!important;background:var(--surface2)!important;
  color:var(--text)!important;transition:all .15s!important;font-size:.86rem!important;
}}
.stDownloadButton>button:hover{{transform:scale(1.03)!important;border-color:{accent}!important;color:{accent}!important;box-shadow:0 4px 16px {accent}33!important;}}

.stSpinner>div{{border-top-color:{accent}!important;}}
.stAlert{{border-radius:.85rem!important;}}
audio{{border-radius:.75rem;width:100%;margin-top:.5rem;}}
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# SESSION STATE
# ─────────────────────────────────────────────────────────────────────────────
def init_state():
    for k, v in {
        'auth_page': 'login',   # 'login' | 'register'
        'dark_mode': True,
        'result': None,
        'auth_status': None,    # True | False | None
        'auth_name': '',
        'auth_username': '',
    }.items():
        if k not in st.session_state:
            st.session_state[k] = v


# ─────────────────────────────────────────────────────────────────────────────
# AUTH HELPERS  (wraps streamlit-authenticator patterns)
# ─────────────────────────────────────────────────────────────────────────────
def get_authenticator():
    import streamlit_authenticator as stauth
    config = load_config()
    auth = stauth.Authenticate(
        config['credentials'],
        config['cookie']['name'],
        config['cookie']['key'],
        config['cookie']['expiry_days'],
        config.get('pre-authorized', {})
    )
    return auth, config


def hash_password(plain: str) -> str:
    import streamlit_authenticator as stauth
    return stauth.Hasher([plain]).generate()[0]


# ─────────────────────────────────────────────────────────────────────────────
# AUTH PAGE  (Login + Register tabs)
# ─────────────────────────────────────────────────────────────────────────────
def render_auth(dark: bool):
    text   = '#e4e4f0' if dark else '#111118'
    muted  = '#64648a' if dark else '#9090aa'
    accent = '#7c6af7' if dark else '#5b50e8'
    accent2= '#a78bfa' if dark else '#764ba2'
    lcrd   = '#13131d' if dark else '#ffffff'
    lbrd   = '#25253a' if dark else '#e2e2ee'

    # floating orb background
    st.markdown("""
<div class="auth-page">
  <div class="orb orb1"></div>
  <div class="orb orb2"></div>
  <div class="orb orb3"></div>
</div>""", unsafe_allow_html=True)

    _, mid, _ = st.columns([1, 1.05, 1])
    with mid:
        # Brand logo
        st.markdown(f"""
<div class="auth-logo">
  <div class="auth-logo-icon">🎵</div>
  <h1 class="auth-brand">InstruNet <span>AI</span></h1>
  <p class="auth-tag">AI Music Instrument Recognition</p>
</div>""", unsafe_allow_html=True)

        # Card wrapper open
        st.markdown(f"""
<div class="auth-card" style="background:{lcrd};border:1px solid {lbrd}">""",
            unsafe_allow_html=True)

        # ── TAB SWITCHER ──
        active_login = st.session_state.auth_page == 'login'
        c1, c2 = st.columns(2)
        with c1:
            if st.button("🔑  Sign In",
                         key="tab_login",
                         use_container_width=True,
                         type="primary" if active_login else "secondary"):
                st.session_state.auth_page = 'login'
                st.rerun()
        with c2:
            if st.button("✨  Create Account",
                         key="tab_reg",
                         use_container_width=True,
                         type="primary" if not active_login else "secondary"):
                st.session_state.auth_page = 'register'
                st.rerun()

        st.markdown("<hr style='border:none;border-top:1px solid var(--border);margin:.5rem 0 1.2rem'>",
                    unsafe_allow_html=True)

        # ── LOGIN FORM ──
        if st.session_state.auth_page == 'login':
            st.markdown(f"""
<p style="font-family:'Syne',sans-serif;font-size:1rem;font-weight:700;color:{text};margin:0 0 .2rem">
  Welcome back 👋
</p>
<p style="font-size:.79rem;color:{muted};margin:0 0 1.2rem">
  Sign in to your InstruNet AI account
</p>""", unsafe_allow_html=True)

            auth, config = get_authenticator()

            # streamlit-authenticator login widget
            auth.login(location='main', key='login_widget')

            status   = st.session_state.get("authentication_status")
            name     = st.session_state.get("name", "")
            username = st.session_state.get("username", "")

            if status is True:
                st.session_state.auth_status   = True
                st.session_state.auth_name     = name
                st.session_state.auth_username = username
                save_config(config)
                st.rerun()

            elif status is False:
                st.markdown(f"""
<div style="background:{"#1f0808" if dark else "#fff1f1"};border:1px solid {"#7f1d1d" if dark else "#fca5a5"};
     border-radius:.75rem;padding:.65rem 1rem;color:{"#fca5a5" if dark else "#dc2626"};
     font-size:.82rem;font-weight:500;margin-top:.5rem;display:flex;align-items:center;gap:.45rem">
  ⚠️ Incorrect username or password. Please try again.
</div>""", unsafe_allow_html=True)

            elif status is None:
                st.markdown(f"""
<p style="font-size:.75rem;color:{muted};text-align:center;margin-top:.5rem">
  Enter your credentials above to sign in.
</p>""", unsafe_allow_html=True)

            st.markdown(f"""
<p style="text-align:center;font-size:.73rem;color:{muted};margin-top:1.2rem">
  Don't have an account? &nbsp;
  <span style="color:{accent};cursor:pointer;font-weight:600">Click "Create Account" above</span>
</p>""", unsafe_allow_html=True)

        # ── REGISTER FORM ──
        else:
            st.markdown(f"""
<p style="font-family:'Syne',sans-serif;font-size:1rem;font-weight:700;color:{text};margin:0 0 .2rem">
  Create your account ✨
</p>
<p style="font-size:.79rem;color:{muted};margin:0 0 1.2rem">
  Sign up to start using InstruNet AI
</p>""", unsafe_allow_html=True)

            new_name  = st.text_input("Full Name",     placeholder="e.g. Alex Johnson",   key="reg_name")
            new_user  = st.text_input("Username",      placeholder="e.g. alexj",           key="reg_user")
            new_email = st.text_input("Email",         placeholder="you@example.com",      key="reg_email")
            new_pass  = st.text_input("Password",      placeholder="Min. 6 characters",    type="password", key="reg_pass")
            new_pass2 = st.text_input("Confirm Password", placeholder="Repeat password",   type="password", key="reg_pass2")

            st.markdown("<div style='height:.3rem'></div>", unsafe_allow_html=True)

            if st.button("Create Account →", use_container_width=True, key="reg_submit"):
                # ── VALIDATION ──
                config  = load_config()
                users   = config["credentials"]["usernames"]
                err     = None

                if not all([new_name, new_user, new_email, new_pass, new_pass2]):
                    err = "Please fill in all fields."
                elif new_user in users:
                    err = f"Username '{new_user}' is already taken. Please choose another."
                elif any(u['email'] == new_email for u in users.values()):
                    err = "An account with this email already exists."
                elif len(new_pass) < 6:
                    err = "Password must be at least 6 characters."
                elif new_pass != new_pass2:
                    err = "Passwords do not match."

                if err:
                    st.markdown(f"""
<div style="background:{"#1f0808" if dark else "#fff1f1"};border:1px solid {"#7f1d1d" if dark else "#fca5a5"};
     border-radius:.75rem;padding:.65rem 1rem;color:{"#fca5a5" if dark else "#dc2626"};
     font-size:.82rem;font-weight:500;margin-top:.5rem;display:flex;align-items:center;gap:.45rem">
  ⚠️ {err}
</div>""", unsafe_allow_html=True)
                else:
                    # Hash password and save
                    hashed = hash_password(new_pass)
                    config["credentials"]["usernames"][new_user] = {
                        "name":                  new_name,
                        "email":                 new_email,
                        "password":              hashed,
                        "failed_login_attempts": 0,
                        "logged_in":             False
                    }
                    save_config(config)
                    st.success("✅ Account created! Switch to Sign In to log in.")
                    st.balloons()

            st.markdown(f"""
<p style="text-align:center;font-size:.73rem;color:{muted};margin-top:1rem">
  Already have an account? &nbsp;
  <span style="color:{accent};cursor:pointer;font-weight:600">Click "Sign In" above</span>
</p>""", unsafe_allow_html=True)

        # Card close
        st.markdown("</div>", unsafe_allow_html=True)

    # Theme toggle
    st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)
    _, tc, _ = st.columns([4, 1.5, 4])
    with tc:
        if st.button("☀️ Light" if dark else "🌙 Dark", key="auth_theme"):
            st.session_state.dark_mode = not dark
            st.rerun()

    st.markdown(f"""
<p style="text-align:center;font-size:.72rem;color:{"rgba(255,255,255,.3)" if dark else "rgba(255,255,255,.5)"};
   margin-top:.5rem">🔒 Passwords are bcrypt-hashed · InstruNet AI © 2026</p>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# AUDIO PROCESSING
# ─────────────────────────────────────────────────────────────────────────────
def process_audio_file(audio_bytes, sr=22050, duration=3.0):
    y, sr = librosa.load(io.BytesIO(audio_bytes), sr=sr, duration=duration, mono=True)
    target = int(sr * duration)
    y = np.pad(y, (0, max(0, target - len(y))), mode='constant')[:target]
    return y, sr

def extract_mel_spectrogram(y, sr, n_mels=128, n_fft=2048, hop_length=512):
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels, n_fft=n_fft, hop_length=hop_length)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    mel_norm = (mel_db - mel_db.min()) / (mel_db.max() - mel_db.min() + 1e-8)
    if mel_norm.shape[1] > 128:
        mel_norm = mel_norm[:, :128]
    elif mel_norm.shape[1] < 128:
        mel_norm = np.pad(mel_norm, ((0,0),(0, 128 - mel_norm.shape[1])), mode='constant')
    return mel_norm


# ─────────────────────────────────────────────────────────────────────────────
# VISUALIZATION
# ─────────────────────────────────────────────────────────────────────────────
def fig_to_b64(fig, dark):
    bg_c = '#15151f' if dark else 'white'
    fig.patch.set_facecolor(bg_c)
    tc = '#64648a' if dark else '#6b7280'
    lc = '#a0a0c0' if dark else '#374151'
    ttc= '#e4e4f0' if dark else '#111118'
    sc = '#2a2a3d' if dark else '#e2e2ee'
    for ax in fig.axes:
        ax.set_facecolor(bg_c)
        ax.tick_params(colors=tc)
        ax.xaxis.label.set_color(lc); ax.yaxis.label.set_color(lc)
        ax.title.set_color(ttc)
        for sp in ax.spines.values(): sp.set_edgecolor(sc)
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=100, bbox_inches='tight', facecolor=bg_c)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode()
    plt.close(fig)
    return f"data:image/png;base64,{b64}"

def gen_waveform(y, sr, dark):
    fig, ax = plt.subplots(figsize=(12, 3))
    ax.plot(np.arange(len(y))/sr, y, color='#7c6af7' if dark else '#3b82f6', linewidth=0.5)
    ax.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax.set_ylabel('Amplitude', fontsize=11, fontweight='bold')
    ax.set_title('Audio Waveform', fontsize=13, fontweight='bold')
    ax.grid(True, alpha=0.12 if dark else 0.25); ax.set_xlim(0, len(y)/sr)
    plt.tight_layout(); return fig_to_b64(fig, dark)

def gen_spectrogram(mel, sr, dark):
    fig, ax = plt.subplots(figsize=(12, 4))
    img = librosa.display.specshow(mel, sr=sr, x_axis='time', y_axis='mel', ax=ax,
                                   cmap='magma' if dark else 'viridis')
    ax.set_title('Mel-Spectrogram', fontsize=13, fontweight='bold')
    ax.set_xlabel('Time (s)', fontsize=11, fontweight='bold')
    ax.set_ylabel('Frequency (Hz)', fontsize=11, fontweight='bold')
    cbar = plt.colorbar(img, ax=ax, format='%+2.0f dB')
    cbar.set_label('Intensity (dB)', fontsize=9)
    tc = '#64648a' if dark else '#6b7280'
    cbar.ax.yaxis.set_tick_params(color=tc)
    plt.setp(cbar.ax.yaxis.get_ticklabels(), color=tc)
    plt.tight_layout(); return fig_to_b64(fig, dark)


# ─────────────────────────────────────────────────────────────────────────────
# PREDICTION
# ─────────────────────────────────────────────────────────────────────────────
def predict_audio(audio_bytes, model, label_encoder, dark):
    y, sr = process_audio_file(audio_bytes)
    mel   = extract_mel_spectrogram(y, sr)
    preds = model.predict(mel.reshape(1,128,128,1), verbose=0)

    inst_p = preds['instrument'][0]
    top3   = [{'name': label_encoder.classes_[i], 'confidence': float(inst_p[i]*100)}
               for i in np.argsort(inst_p)[::-1][:3]]

    qi = np.argmax(preds['quality'][0])
    quality = {
        'label': QUALITY_LABELS[qi],
        'confidence': float(preds['quality'][0][qi]*100),
        'all_scores': {QUALITY_LABELS[i]: float(preds['quality'][0][i]*100) for i in range(4)}
    }
    ci = np.argmax(preds['condition'][0])
    condition = {
        'label': CONDITION_LABELS[ci],
        'confidence': float(preds['condition'][0][ci]*100),
        'all_scores': {CONDITION_LABELS[i]: float(preds['condition'][0][i]*100) for i in range(4)}
    }
    return {
        'instrument': top3[0], 'top_instruments': top3,
        'quality': quality, 'condition': condition,
        'visualizations': {'waveform': gen_waveform(y, sr, dark),
                           'spectrogram': gen_spectrogram(mel, sr, dark)},
        'audio_info': {'duration': float(len(y)/sr), 'sample_rate': int(sr), 'samples': len(y)},
        'timestamp': datetime.now().isoformat()
    }


# ─────────────────────────────────────────────────────────────────────────────
# PDF
# ─────────────────────────────────────────────────────────────────────────────
def generate_pdf_bytes(result):
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.units import inch
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter)
    story, styles = [], getSampleStyleSheet()
    ts = ParagraphStyle('T', parent=styles['Heading1'], fontSize=22,
                        textColor=colors.HexColor('#1e40af'), spaceAfter=26, alignment=1)
    story.append(Paragraph("Audio Analysis Report — InstruNet AI", ts))
    story.append(Spacer(1, .28*inch))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y at %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, .2*inch))
    def mkt(data, cw, hc):
        t = Table(data, colWidths=cw)
        t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0),colors.HexColor(hc)),
            ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),
            ('ALIGN',(0,0),(-1,-1),'CENTER'),
            ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
            ('FONTSIZE',(0,0),(-1,0),11),
            ('BOTTOMPADDING',(0,0),(-1,0),10),
            ('BACKGROUND',(0,1),(-1,-1),colors.beige),
            ('GRID',(0,0),(-1,-1),1,colors.black),
        ]))
        return t
    ai = result['audio_info']
    for heading, data, cw, hc in [
        ("INSTRUMENT PREDICTION",
         [['Instrument','Confidence'],[result['instrument']['name'].upper(), f"{result['instrument']['confidence']:.1f}%"]],
         [3*inch,2*inch],'#3b82f6'),
        ("AUDIO QUALITY",
         [['Quality','Confidence'],[result['quality']['label'].upper(), f"{result['quality']['confidence']:.1f}%"]],
         [3*inch,2*inch],'#10b981'),
        ("AUDIO CONDITION",
         [['Condition','Confidence'],[result['condition']['label'].upper(), f"{result['condition']['confidence']:.1f}%"]],
         [3*inch,2*inch],'#f59e0b'),
        ("AUDIO INFORMATION",
         [['Property','Value'],['Duration',f"{ai['duration']:.2f}s"],
          ['Sample Rate',f"{ai['sample_rate']} Hz"],['Samples',f"{ai['samples']:,}"]],
         [3*inch,2*inch],'#6b7280'),
    ]:
        story.append(Paragraph(f"<b>{heading}</b>", styles['Heading2']))
        story.append(mkt(data, cw, hc)); story.append(Spacer(1,.25*inch))
    story.append(Paragraph("<b>Top 3 Predictions</b>", styles['Heading3']))
    t3 = [['Rank','Instrument','Confidence']]
    for i, x in enumerate(result['top_instruments'],1):
        t3.append([str(i), x['name'].capitalize(), f"{x['confidence']:.1f}%"])
    story.append(mkt(t3,[1*inch,2*inch,2*inch],'#6366f1'))
    doc.build(story); buf.seek(0); return buf.read()


# ─────────────────────────────────────────────────────────────────────────────
# RENDER HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def gauge_svg(val, size=200, stroke=15, label='', dark=True):
    import math
    r=( size-stroke)/2; cx=cy=size/2; c=2*math.pi*r; arc=c*.75
    off=arc-(val/100)*arc
    col='#10b981' if val>=80 else '#f59e0b' if val>=50 else '#ef4444'
    trk='#252535' if dark else '#e2e2ee'
    rot=f"rotate(-225 {cx} {cy})"
    lb=(f'<text x="{cx}" y="{size-5}" text-anchor="middle" font-size="10" font-weight="700" '
        f'fill="{trk}" font-family="DM Sans,sans-serif">{label.upper()}</text>') if label else ''
    return (f'<svg width="{size}" height="{size}" style="overflow:visible">'
            f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="{trk}" stroke-width="{stroke}" '
            f'stroke-linecap="round" stroke-dasharray="{arc:.2f} {c:.2f}" transform="{rot}"/>'
            f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" stroke="{col}" stroke-width="{stroke}" '
            f'stroke-linecap="round" stroke-dasharray="{arc:.2f} {c:.2f}" stroke-dashoffset="{off:.2f}" '
            f'transform="{rot}" style="filter:drop-shadow(0 0 6px {col}99)"/>'
            f'<text x="{cx}" y="{cy-4}" text-anchor="middle" font-size="21" font-weight="800" '
            f'fill="{col}" font-family="Syne,sans-serif">{val:.1f}%</text>'
            f'<text x="{cx}" y="{cy+14}" text-anchor="middle" font-size="10" font-weight="500" '
            f'fill="{trk}" font-family="DM Sans,sans-serif">CONFIDENCE</text>{lb}</svg>')

def abar(v, col, h=8):
    return (f'<div class="bar-track" style="height:{h}px"><div class="bar-fill" '
            f'style="height:{h}px;width:{v:.1f}%;background:{col};box-shadow:0 0 7px {col}55"></div></div>')

def render_hero(r, dark):
    inst=r['instrument']; icon=get_icon(inst['name']); conf=inst['confidence']
    ccls='ch' if conf>=80 else 'cm' if conf>=50 else 'cl'
    clbl='✅ High Confidence' if conf>=80 else '⚠️ Moderate Confidence' if conf>=50 else '❌ Low Confidence'
    gsvg=gauge_svg(conf,200,16,dark=dark)
    acc='#7c6af7' if dark else '#5b50e8'
    tc='#e4e4f0' if dark else '#111118'; mu='#64648a' if dark else '#9090aa'
    cards=''
    for i,item in enumerate(r['top_instruments']):
        wc='win' if i==0 else ''; rc='r1' if i==0 else 'rn'
        bc=acc if i==0 else ('#35355a' if dark else '#c8c8dd')
        cards+=(f'<div class="pcard {wc}"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:.68rem">'
                f'<span class="rbadge {rc}">#{i+1}</span><span style="font-size:1.38rem">{get_icon(item["name"])}</span></div>'
                f'<p style="font-family:Syne,sans-serif;font-weight:700;color:{tc};font-size:.97rem;text-transform:capitalize;margin:.18rem 0">{item["name"]}</p>'
                f'<div style="display:flex;justify-content:space-between;font-size:.77rem;margin-bottom:.36rem">'
                f'<span style="color:{mu}">Confidence</span><span style="font-weight:800;color:{tc}">{item["confidence"]:.1f}%</span></div>'
                f'{abar(item["confidence"],bc,8)}</div>')
    st.markdown(f'<div class="card"><h3 style="font-size:1.22rem;border-bottom:1px solid var(--border);padding-bottom:.82rem;margin-bottom:1.25rem">📊 Analysis Results</h3>'
                f'<div class="hero-wrap"><div>{gsvg}</div><div><div class="hero-icon">{icon}</div>'
                f'<div class="hero-name">{inst["name"].upper()}</div>'
                f'<div class="hero-sub">Top Prediction</div><div class="{ccls}">{clbl}</div></div></div>'
                f'<p style="font-size:.74rem;font-weight:700;color:{mu};text-transform:uppercase;letter-spacing:.09em;margin-bottom:.68rem">🔢 All Predictions</p>'
                f'<div class="pgrid">{cards}</div></div>', unsafe_allow_html=True)

def render_quality(q, dark):
    lbl=q['label']; conf=q['confidence']; gsvg=gauge_svg(conf,170,14,lbl,dark)
    mu='#64648a' if dark else '#9090aa'; bars=''
    for l,s in q['all_scores'].items():
        w=l==lbl; col='#10b981' if w else ('#35355a' if dark else '#d1d5db')
        fw='font-weight:700;color:#10b981' if w else f'color:{mu}'
        bars+=(f'<div class="bar-row"><div class="bar-label">'
               f'<span style="{fw};text-transform:capitalize;font-size:.79rem">{"▶ " if w else ""}{l}</span>'
               f'<span style="{fw};font-size:.79rem">{s:.1f}%</span></div>{abar(s,col,8)}</div>')
    st.markdown(f'<div class="card" style="height:100%"><h3>🎚️ Audio Quality</h3>'
                f'<div style="display:flex;flex-direction:column;align-items:center;margin-bottom:.88rem">'
                f'{gsvg}<span class="qbadge q-{lbl.lower()}" style="margin-top:.68rem">{lbl.upper()}</span>'
                f'</div>{bars}</div>', unsafe_allow_html=True)

def render_condition(cond, dark):
    cs=cond.get('all_scores',{})
    ms=cs.get('modern',0)+cs.get('clean',0)+cs.get('noisy',0); vs=cs.get('vintage',0)
    et=ms+vs or 1; mp=(ms/et)*100; vp=(vs/et)*100; im=ms>=vs
    nr=cs.get('noisy',0); cr=cs.get('clean',0); isn=nr>cr
    mu='#64648a' if dark else '#9090aa'; sc='#ef4444' if isn else '#10b981'
    meb=(f'<span style="margin-left:.28rem;padding:.08rem .48rem;background:{"#1e1b4b" if dark else "#dbeafe"};'
         f'color:{"#818cf8" if dark else "#2563eb"};border-radius:9999px;font-size:.66rem;font-weight:700">ERA</span>') if im else ''
    veb=(f'<span style="margin-left:.28rem;padding:.08rem .48rem;background:{"#431407" if dark else "#fef3c7"};'
         f'color:#fb923c;border-radius:9999px;font-size:.66rem;font-weight:700">ERA</span>') if not im else ''
    mc='#818cf8' if dark else '#3b82f6'
    sub=''
    for l,s,c,tc2 in [('Clean signal',cr,'#2dd4bf','#0d9488'),('Noisy signal',nr,'#f87171','#dc2626')]:
        sub+=(f'<div style="display:flex;align-items:center;gap:.48rem;margin-bottom:.3rem">'
              f'<span style="font-size:.7rem;color:{mu};width:84px;flex-shrink:0">{l}</span>'
              f'<div style="flex:1">{abar(s,c,6)}</div>'
              f'<span style="font-size:.7rem;font-weight:700;color:{tc2};width:34px;text-align:right">{s:.1f}%</span></div>')
    st.markdown(
        f'<div class="card" style="height:100%"><h3>⏳ Audio Condition</h3>'
        f'<p style="font-size:.66rem;font-weight:700;color:{mu};text-transform:uppercase;letter-spacing:.08em;margin-bottom:.68rem">🕰️ Recording Era</p>'
        f'<div class="bar-row"><div class="bar-label">'
        f'<span style="font-weight:700;color:{"#818cf8" if im and dark else "#2563eb" if im else mu};font-size:.79rem">💿 Modern {meb}</span>'
        f'<span style="font-weight:800;color:{"#818cf8" if im and dark else "#2563eb" if im else mu};font-size:.79rem">{mp:.1f}%</span></div>{abar(mp,mc,16)}</div>'
        f'<div class="bar-row" style="margin-top:.68rem"><div class="bar-label">'
        f'<span style="font-weight:700;color:{"#fb923c" if not im else mu};font-size:.79rem">🕰️ Vintage {veb}</span>'
        f'<span style="font-weight:800;color:{"#fb923c" if not im else mu};font-size:.79rem">{vp:.1f}%</span></div>{abar(vp,"#fb923c",16)}</div>'
        f'<p style="font-size:.66rem;font-weight:700;color:{mu};text-transform:uppercase;letter-spacing:.08em;margin:1.1rem 0 .52rem">🔊 Signal Quality</p>'
        f'<div class="sigbox {"snoisy" if isn else "sclean"}">'
        f'<div style="display:flex;align-items:center;gap:.68rem">'
        f'<span style="font-size:1.32rem">{"📻" if isn else "✨"}</span>'
        f'<div><p style="font-size:.88rem;font-weight:800;color:{sc};margin:0">{"Noisy" if isn else "Clean"}</p>'
        f'<p style="font-size:.7rem;color:{mu};margin:.1rem 0 0">{"Background noise or artifacts detected" if isn else "Clear signal with minimal noise"}</p>'
        f'</div></div><span style="font-size:1.32rem">{"⚠️" if isn else "✅"}</span></div>'
        f'<div style="padding:0 .12rem">{sub}</div></div>', unsafe_allow_html=True)

def render_info(result):
    ai=result['audio_info']
    st.markdown(f'<div class="card"><h3>ℹ️ Audio Information</h3><div class="igrid">'
                f'<div class="itile tb"><div class="t-ico">⏱️</div><div class="t-lbl">Duration</div><div class="t-val">{ai["duration"]:.2f}s</div></div>'
                f'<div class="itile tp"><div class="t-ico">〰️</div><div class="t-lbl">Sample Rate</div><div class="t-val">{ai["sample_rate"]} Hz</div></div>'
                f'<div class="itile ti"><div class="t-ico">💾</div><div class="t-lbl">Samples</div><div class="t-val">{ai["samples"]:,}</div></div>'
                f'</div></div>', unsafe_allow_html=True)
    ts=datetime.now().strftime('%Y%m%d_%H%M%S')
    c1,c2=st.columns(2)
    with c1: st.download_button("⬇️  Download JSON",
        data=json.dumps({k:v for k,v in result.items() if k!='visualizations'},indent=2),
        file_name=f"instrunet_{ts}.json",mime="application/json",use_container_width=True)
    with c2: st.download_button("📄  Download PDF",data=generate_pdf_bytes(result),
        file_name=f"instrunet_{ts}.pdf",mime="application/pdf",use_container_width=True)

def render_viz(result):
    st.markdown(f'<div class="card"><h3>〰️ Audio Visualizations</h3>'
                f'<p style="font-size:.66rem;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;margin-bottom:.42rem">Waveform</p>'
                f'<img src="{result["visualizations"]["waveform"]}" class="viz-img" style="margin-bottom:1.32rem"/>'
                f'<p style="font-size:.66rem;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;margin-bottom:.42rem">Mel-Spectrogram</p>'
                f'<img src="{result["visualizations"]["spectrogram"]}" class="viz-img"/></div>',
                unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN APP
# ─────────────────────────────────────────────────────────────────────────────
def render_app(dark: bool):
    text='#e4e4f0' if dark else '#111118'; muted='#64648a' if dark else '#9090aa'

    load_model_and_encoder()  # silent pre-load, cached

    # Header
    st.markdown('<div class="hdr"><h1>🎵 InstruNet <span>AI</span></h1>'
                '<p>AI-Powered Music Instrument Recognition &amp; Analysis</p>'
                '<div class="tag-row"><span class="tag-pill">Instrument</span>'
                '<span class="tag-pill">Quality</span><span class="tag-pill">Condition</span>'
                '<span class="tag-pill">Multi-Task CNN</span></div></div>',
                unsafe_allow_html=True)

    # User bar — name, theme toggle, sign-out
    cu, ct, clo = st.columns([6, 1.6, 1.2])
    with cu:
        name = st.session_state.get('auth_name') or st.session_state.get('name','User')
        st.markdown(f'<div style="padding:.5rem 2.5rem;font-size:.79rem;color:{muted};'
                    f'background:{"#1c1c28" if dark else "#f7f7fc"};border-bottom:1px solid {"#2a2a3d" if dark else "#e2e2ee"}">'
                    f'👤 Signed in as <strong style="color:{text}">{name}</strong></div>',
                    unsafe_allow_html=True)
    with ct:
        if st.button("☀️ Light" if dark else "🌙 Dark", key="app_theme"):
            st.session_state.dark_mode = not dark
            st.session_state.result = None
            st.rerun()
    with clo:
        auth, config = get_authenticator()
        auth.logout(button_name="Sign Out", location='main', key='signout_btn')
        # After logout, clear our state too
        if not st.session_state.get("authentication_status"):
            st.session_state.auth_status = None
            st.session_state.auth_name   = ''
            save_config(config)
            st.rerun()

    st.markdown('<div class="wrap">', unsafe_allow_html=True)

    # Upload
    st.markdown('<div class="card"><h3>☁️ Upload Audio File</h3>', unsafe_allow_html=True)
    af = st.file_uploader("Drop audio file here or click to browse — WAV · MP3 · OGG · First 3 seconds analyzed",
                          type=['wav','mp3','ogg','flac','m4a'], label_visibility='visible')
    if af:
        st.audio(af, format=af.type)
        st.markdown(f'<div style="display:flex;align-items:center;gap:.68rem;padding:.62rem 1rem;'
                    f'background:{"#0c1a10" if dark else "#f0fff4"};border-radius:.85rem;'
                    f'border:1px solid {"#166534" if dark else "#86efac"};margin-top:.68rem">'
                    f'<span style="font-size:1.05rem">✅</span>'
                    f'<div><p style="font-weight:600;color:{text};font-size:.84rem;margin:0">{af.name}</p>'
                    f'<p style="font-size:.7rem;color:{muted};margin:0">{af.size/1024:.2f} KB</p></div></div>',
                    unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    _, cc, _ = st.columns([2,2,2])
    with cc:
        go = st.button("🧠  Analyze Audio", disabled=af is None, use_container_width=True)

    if go and af:
        with st.spinner("🔬 Analyzing audio…"):
            model, le = load_model_and_encoder()
            result = predict_audio(af.read(), model, le, dark)
        st.session_state.result = result

    if st.session_state.result:
        res=st.session_state.result
        render_hero(res, dark)
        c1,c2=st.columns(2)
        with c1: render_quality(res['quality'], dark)
        with c2: render_condition(res['condition'], dark)
        render_info(res)
        render_viz(res)

    st.markdown('</div>', unsafe_allow_html=True)
    st.markdown('<div class="ftr">© 2026 InstruNet AI &nbsp;·&nbsp; Multi-Task CNN · Instrument · Quality · Condition</div>',
                unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
def main():
    init_state()
    dark = st.session_state.dark_mode
    inject_css(dark)

    # Check if already authenticated via cookie (streamlit-authenticator handles this)
    try:
        auth, config = get_authenticator()
        auth.login(location='unrendered', key='cookie_check')
    except Exception:
        pass

    is_auth = (st.session_state.get("authentication_status") is True
               or st.session_state.auth_status is True)

    if is_auth:
        render_app(dark)
    else:
        render_auth(dark)


if __name__ == '__main__':
    main()

